# Generated by Django 5.1.3 on 2024-12-27 10:50

from django.db import migrations, models

import django_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demomodel_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='html',
            field=django_admin.models.HTMLField(blank=True, help_text='Enter html', null=True, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='file',
            field=models.FileField(help_text='Allowed file types: Any | Max file size in MB: [None]', upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='image',
            field=models.ImageField(help_text="Allowed file types: ['.jpg', '.jpeg', '.png'] | Max file size in MB: [2]", upload_to='', verbose_name='Image'),
        ),
    ]
