# Generated by Django 5.1.3 on 2025-01-08 11:58

import django.db.models.deletion
from django.db import migrations, models

import django_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_demomodel_html_alter_demomodel_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter country', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Enter level', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='file',
            field=models.FileField(help_text='Allowed file types: [Any] | Max file size in MB: [None]', upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='html',
            field=django_admin.models.HTMLField(default='', help_text='Enter html', verbose_name='HTML'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.PositiveIntegerField(help_text='Enter area number')),
                ('country', models.OneToOneField(help_text='Select country', on_delete=django.db.models.deletion.CASCADE, to='demo.country')),
                ('type', models.ForeignKey(help_text='Select type', on_delete=django.db.models.deletion.CASCADE, to='demo.type')),
                ('level', models.ForeignKey(help_text='Select level', on_delete=django.db.models.deletion.CASCADE, to='demo.level')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
