# Generated by Django 5.1.3 on 2025-01-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_country_level_alter_demomodel_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
