# Generated by Django 5.1.3 on 2025-01-18 09:15

from django.db import migrations, models

import django_admin.models
import django_admin_documentation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_model_name', models.CharField(choices=django_admin_documentation.models.get_app_model_choices, help_text='The app - model name', max_length=50)),
                ('content', django_admin.models.HTMLField(help_text='Enter content here')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
