# Generated by Django 5.1.3 on 2025-01-18 09:55

from django.db import migrations, models

import django_admin_documentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldocumentation',
            name='app_model_name',
            field=models.CharField(choices=django_admin_documentation.models.get_app_model_choices, help_text='The app - model name', max_length=50, unique=True),
        ),
    ]
