# Generated by Django 5.1.3 on 2024-12-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_admin_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission', verbose_name='Permissions'),
        ),
    ]
