# Generated by Django 5.1.3 on 2025-02-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedquerybuilder',
            name='name',
            field=models.CharField(help_text='The name of the query', max_length=100, unique=True),
        ),
    ]
