# Generated by Django 5.1.3 on 2025-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_queries', '0002_alter_savedquerybuilder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRawQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The name of the query', max_length=100, unique=True)),
                ('query', models.TextField(verbose_name='query')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
