# Generated by Django 5.1.3 on 2024-12-20 12:52

import django.core.validators
import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uid', models.CharField(default=users.models.generate_user_id, editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='UID')),
                ('email', models.EmailField(default='', help_text='Enter a valid email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address')], verbose_name='Email Address')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('password', models.CharField(help_text='Must be at least 8 characters and must have at least 1 digit', max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and contain at least one digit.', regex='^(?=.*\\d).{8,}$')], verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(blank=True, default=False, verbose_name='Is Active')),
                ('is_superuser', models.BooleanField(blank=True, default=False, verbose_name='Is Superuser')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='Is Staff')),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Login')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
