from django.urls import path

from .views import (
    add_model_record,
    change_model_record,
    custom_action_view,
    delete_model_record,
    delete_queued_jobs,
    get_apps,
    get_content_types,
    get_failed_queued_jobs,
    get_groups,
    get_inline_listview,
    get_log_entries,
    get_model_admin_settings,
    get_model_fields,
    get_model_fields_edit,
    get_model_listview,
    get_model_record,
    get_permissions,
    get_queued_job,
    get_worker_queues,
    requeue_failed_jobs,
    verify_cloudflare_token,
)
from .views_documentation import get_model_docs
from .views_saved_queries import (
    add_query_builder,
    add_raw_query,
    change_query_builder,
    change_raw_query,
    delete_query_builder,
    delete_raw_query,
    get_all_query_builders,
    get_all_raw_queries,
    query_builder,
    raw_query,
)
from .views_users import (
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    get_all_users,
    get_user_detail,
    get_user_permissions,
    logout,
    reset_password_via_link,
    send_password_reset_link,
    verify_password_reset_link,
)

urlpatterns = [
    path('apps', get_apps, name='get_apps'),
    path('permissions', get_permissions, name='get_permissions'),
    path('log-entries', get_log_entries, name='get_log_entries'),
    path('content-types', get_content_types, name='get_content_types'),
    path('groups', get_groups, name='get_groups'),
    path('model-listview-action/<str:app_label>/<str:model_name>/<str:func>', custom_action_view, name='custom_action_view'),
    path('model-listview/<str:app_label>/<str:model_name>', get_model_listview, name='get_model_listview'),
    path('inline-listview/<str:parent_app_label>/<str:parent_model_name>/<change_obj_pk>', get_inline_listview, name='get_inline_listview'),
    path('add-record/<str:app_label>/<str:model_name>', add_model_record, name='add_model_record'),
    path('change-record/<str:app_label>/<str:model_name>/<str:pk>', change_model_record, name='change_model_record'),
    path('delete-record/<str:app_label>/<str:model_name>/<str:pk>', delete_model_record, name='delete_model_record'),
    path('model/<str:app_label>/<str:model_name>/<str:pk>', get_model_record, name='get_model_record'),
    path('model-fields/<str:app_label>/<str:model_name>/<str:pk>', get_model_fields_edit, name='get_model_fields_edit'),
    path('model-fields/<str:app_label>/<str:model_name>', get_model_fields, name='get_model_fields'),
    path('model-admin-settings/<str:app_label>/<str:model_name>/<str:pk>', get_model_admin_settings, name='get_model_admin_settings'),
    path('verify-cloudflare-token', verify_cloudflare_token, name='verify_cloudflare_token'),
    path('worker-queues', get_worker_queues, name='get_worker_queues'),
    path('worker-failed-jobs/<str:queue_name>', get_failed_queued_jobs, name='get_failed_queued_jobs'),
    path('worker-jobs/requeue', requeue_failed_jobs, name='requeue_failed_jobs'),
    path('worker-jobs/delete', delete_queued_jobs, name='delete_queued_jobs'),
    path('worker-jobs/<str:queue_name>/<str:job_id>', get_queued_job, name='get_queued_job'),

    # documentation urls
    path('model-docs', get_model_docs, name='get_model_docs'),

    # saved_queries urls
    path('saved-queries/query-builder/change/<int:id>', change_query_builder, name='change_query_builder'),
    path('saved-queries/query-builder/delete/<int:id>', delete_query_builder, name='delete_query_builder'),
    path('saved-queries/query-builder/add', add_query_builder, name='add_query_builder'),
    path('saved-queries/query-builder/get-data', query_builder, name='query_builder'),
    path('saved-queries/query-builder', get_all_query_builders, name='get_all_query_builders'),
    path('saved-queries/raw-query/get-data', raw_query, name='raw_query'),
    path('saved-queries/raw-query/change/<int:id>', change_raw_query, name='change_raw_query'),
    path('saved-queries/raw-query/delete/<int:id>', delete_raw_query, name='delete_raw_query'),
    path('saved-queries/raw-query/add', add_raw_query, name='add_raw_query'),
    path('saved-queries/raw-query', get_all_raw_queries, name='get_all_raw_queries'),

    # users urls
    path('users/login', CustomTokenObtainPairView.as_view(), name='login'),
    path('users/refresh-token', CustomTokenRefreshView.as_view(), name='refresh_token'),
    path('users/logout', logout, name='logout'),
    path('users/send-password-reset-link/<str:uid>', send_password_reset_link, name='send_password_reset_link'),
    path('users/verify-password-reset-link/<str:uidb64>/<str:token>', verify_password_reset_link, name='verify_password_reset_link'),
    path('users/reset-password-via-link/<str:uidb64>/<str:token>', reset_password_via_link, name='reset_password_via_link'),
    path('users/permissions/<str:uid>', get_user_permissions, name='get_user_permissions'),
    path('users/<str:uid>', get_user_detail, name='get_user_detail'),
    path('users', get_all_users, name='get_all_users'),
]
